version: "3.5"

services:
  db:
    image: mysql
    #build: ./compose/node
    volumes:
      - "./volume/mysql:/var/lib/mysql"
      - "./compose/mysql/init:/docker-entrypoint-initdb.d"
      - "./compose/mysql/my.cnf:/etc/my.cnf"
    ports:
      - 3366:3306
    environment:
      MYSQL_DATABASE: temp
      MYSQL_USER: tempuser
      MYSQL_PASSWORD: password 
      MYSQL_ROOT_PASSWORD: password
      TZ : Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  phpmyadmin:
    #build: ./compose/phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    links:
      - db
    ports:
       - 8080:80
    volumes:
       - "./volume/phpmyadmin/sessions:/sessions"
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  front:
    #image: node:16.8
    build: ./compose/node/
    volumes: 
      - ./volume/node:/home/node/work
    ports:
      - 3001:3000
    tty: true
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24